-- sequences
-- Sequence: SEQFACTURA
CREATE SEQUENCE SEQFACTURA
      INCREMENT BY 1
      MINVALUE 1
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- Sequence: SEQFACTURADETALLES
CREATE SEQUENCE SEQFACTURADETALLES
      INCREMENT BY 1
      MINVALUE 1
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- Sequence: SEQLLAMADAS
CREATE SEQUENCE SEQLLAMADAS
      INCREMENT BY 1
      MINVALUE 1
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- Sequence: SEQRECARGA
CREATE SEQUENCE SEQRECARGA
      INCREMENT BY 1
      MINVALUE 1
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- End of file.